### ISSUE TITLE
Bugs saisie formulaire

### ISSUE THREAD

**Issue by HerveParis** [TheCitizenCrew/RentsPrices#14]
Ola! petits bugs
1 - Pas réussi à créer une nouvelle adresse (message : Whoops, looks like something went wrong.) tandis que j'ai pu facilement corriger une adresse existante
2 - Lors de la saisie du formulaire, si on corrige le numéro de rue (si on s’est trompé par exemple) le nouveau numéro n’est pas pris en compte (X,Y) sur la carte de localisation

**Comment by Cyrille37** [comment]
Je regarde de suite.

**Comment by Cyrille37** [comment]
J'ai splité ce rapport en 2 : 
- #17 
- #15
