### ISSUE TITLE
creation nouvelle adresse => plantage et complément #20

### ISSUE THREAD

**Issue by HerveParis** [TheCitizenCrew/RentsPrices#21]
ola!
- je ne suis aps parvenu à créer une nouvelle adresse alors que je suis parvenu sans problème à modifier une des adresses existantes. 
- lorsqu'on modifie un formulaire existant, le bug #20 ne se produit pas

**Comment by Cyrille37** [comment]
je n'arrive pas à reproduire le problème

**Comment by HerveParis** [comment]
problème n'existe plus :-) sais pas ce qui s'est passé
bravo à toi en tout cas

**Comment by HerveParis** [comment]
Bonjour Cyrille
j'ai maintenant identifié plus clairement ce qui pose problème : 
ça marche bien quand on crée une adresse et qu'on enregistre l'adresse avant de saisir un loyer.
En revanche si on saisi le loyer en même temps que l'on crée l'adresse , ça plante :/)

**Comment by HerveParis** [comment]
clos l'issue par erreur

**Comment by Cyrille37** [comment]
Il y avait un problème avec la relation et la gestion de la transaction.
Est-ce que ça va mieux comme ça ?

**Comment by HerveParis** [comment]
top c'est nickel !

**Comment by HerveParis** [comment]
Top!
ça marche très bien
merci Cyrille
H

Le 10/07/2015 14:57, Cyrille Giquello a écrit :

> Il y avait un problème avec la relation et la gestion de la transaction.
> Est-ce que ça va mieux comme ça ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/TheCitizenCrew/RentsPrices/issues/21#issuecomment-120404353.

## 

---

Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
https://www.avast.com/antivirus

**Comment by Cyrille37** [comment]
ouf ;-)

**Comment by HerveParis** [comment]
olala!
:D

Le 11/07/2015 11:33, Cyrille Giquello a écrit :

> ouf ;-)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/TheCitizenCrew/RentsPrices/issues/21#issuecomment-120598968.

## 

---

Ce courrier électronique ne contient aucun virus ou logiciel malveillant parce que la protection avast! Antivirus est active.
https://www.avast.com/antivirus
